### ISSUE TITLE
ValueError: No such layer: avg_pool

### ISSUE THREAD

**Issue by MAdil45** [wangzwhu/CSR-GAN#1]
Hello @wangzwhu . I am really impressed with your work. Great idea for implementing GAN to improve the resolution and then putting re identification network to Reid a person. 
I am trying to implement this code but i am kind of stuck into this issue. I tried upgrading keras but it didn't work. Kindly as a professional courtesy, help me out of this. I'll really appreciate your positive response.

Traceback (most recent call last):
  File "get_feature_viper.py", line 114, in <module>
    evaluate()
  File "get_feature_viper.py", line 57, in evaluate
    net = Model(input=net.input, output= [net.get_layer('avg_pool').output])
  File "/home/adil/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1891, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: avg_pool

**Comment by xixi9619** [comment]
hi i‘m now facing the same issue, have you solved it? 
Thanks!

**Comment by xixi9619** [comment]
> Hello @wangzwhu . I am really impressed with your work. Great idea for implementing GAN to improve the resolution and then putting re identification network to Reid a person.
> I am trying to implement this code but i am kind of stuck into this issue. I tried upgrading keras but it didn't work. Kindly as a professional courtesy, help me out of this. I'll really appreciate your positive response.
> 
> Traceback (most recent call last):
> File "get_feature_viper.py", line 114, in 
> evaluate()
> File "get_feature_viper.py", line 57, in evaluate
> net = Model(input=net.input, output= [net.get_layer('avg_pool').output])
> File "/home/adil/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1891, in get_layer
> raise ValueError('No such layer: ' + name)
> ValueError: No such layer: avg_pool

hi i‘m now facing the same issue, have you solved it?
Thanks!

**Comment by MAdil45** [comment]
@xixi9619  No. I didn't. Have you?? I left it. But if you solved it then kindly let me know about it.

**Comment by celihome** [comment]
do you facing this issue?
Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 222, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "F:\anaconda\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "F:\anaconda\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "F:\anaconda\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "F:\anaconda\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "F:\anaconda\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "F:\anaconda\lib\urllib\request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 359, in <module>
    train()
  File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 100, in train
    base_model = ResNet50(weights='imagenet', include_top=False, input_tensor=Input(shape=(224,224,3)))
  File "F:\anaconda\lib\site-packages\keras\applications\__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\keras\applications\resnet50.py", line 11, in ResNet50
    return resnet50.ResNet50(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\keras_applications\resnet50.py", line 290, in ResNet50
    md5_hash='a268eb855778b3df3c7506639542a6af')
  File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 226, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- unknown url type: https

**Comment by celihome** [comment]
do you facing this issue?
Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 222, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "F:\anaconda\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "F:\anaconda\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "F:\anaconda\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "F:\anaconda\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "F:\anaconda\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "F:\anaconda\lib\urllib\request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 359, in <module>
    train()
  File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 100, in train
    base_model = ResNet50(weights='imagenet', include_top=False, input_tensor=Input(shape=(224,224,3)))
  File "F:\anaconda\lib\site-packages\keras\applications\__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\keras\applications\resnet50.py", line 11, in ResNet50
    return resnet50.ResNet50(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\keras_applications\resnet50.py", line 290, in ResNet50
    md5_hash='a268eb855778b3df3c7506639542a6af')
  File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 226, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- unknown url type: https

**Comment by celihome** [comment]
> Hello @wangzwhu . I am really impressed with your work. Great idea for implementing GAN to improve the resolution and then putting re identification network to Reid a person.
> I am trying to implement this code but i am kind of stuck into this issue. I tried upgrading keras but it didn't work. Kindly as a professional courtesy, help me out of this. I'll really appreciate your positive response.
> Traceback (most recent call last):
> File "get_feature_viper.py", line 114, in 
> evaluate()
> File "get_feature_viper.py", line 57, in evaluate
> net = Model(input=net.input, output= [net.get_layer('avg_pool').output])
> File "/home/adil/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1891, in get_layer
> raise ValueError('No such layer: ' + name)
> ValueError: No such layer: avg_pool

do you facing this issue?
Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 222, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "F:\anaconda\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "F:\anaconda\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "F:\anaconda\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "F:\anaconda\lib\urllib\request.py", line 548, in _open
    'unknown_open', req)
  File "F:\anaconda\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "F:\anaconda\lib\urllib\request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 359, in <module>
    train()
  File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 100, in train
    base_model = ResNet50(weights='imagenet', include_top=False, input_tensor=Input(shape=(224,224,3)))
  File "F:\anaconda\lib\site-packages\keras\applications\__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\keras\applications\resnet50.py", line 11, in ResNet50
    return resnet50.ResNet50(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\keras_applications\resnet50.py", line 290, in ResNet50
    md5_hash='a268eb855778b3df3c7506639542a6af')
  File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 226, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- unknown url type: https

**Comment by MAdil45** [comment]
> > Hello @wangzwhu . I am really impressed with your work. Great idea for implementing GAN to improve the resolution and then putting re identification network to Reid a person.
> > I am trying to implement this code but i am kind of stuck into this issue. I tried upgrading keras but it didn't work. Kindly as a professional courtesy, help me out of this. I'll really appreciate your positive response.
> > Traceback (most recent call last):
> > File "get_feature_viper.py", line 114, in
> > evaluate()
> > File "get_feature_viper.py", line 57, in evaluate
> > net = Model(input=net.input, output= [net.get_layer('avg_pool').output])
> > File "/home/adil/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1891, in get_layer
> > raise ValueError('No such layer: ' + name)
> > ValueError: No such layer: avg_pool
> 
> do you facing this issue?
> Traceback (most recent call last):
> File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 222, in get_file
> urlretrieve(origin, fpath, dl_progress)
> File "F:\anaconda\lib\urllib\request.py", line 247, in urlretrieve
> with contextlib.closing(urlopen(url, data)) as fp:
> File "F:\anaconda\lib\urllib\request.py", line 222, in urlopen
> return opener.open(url, data, timeout)
> File "F:\anaconda\lib\urllib\request.py", line 525, in open
> response = self._open(req, data)
> File "F:\anaconda\lib\urllib\request.py", line 548, in _open
> 'unknown_open', req)
> File "F:\anaconda\lib\urllib\request.py", line 503, in _call_chain
> result = func(*args)
> File "F:\anaconda\lib\urllib\request.py", line 1387, in unknown_open
> raise URLError('unknown url type: %s' % type)
> urllib.error.URLError:
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 359, in 
> train()
> File "F:/py代码/python/CSR-GAN-master/train_csr_gan_viper.py", line 100, in train
> base_model = ResNet50(weights='imagenet', include_top=False, input_tensor=Input(shape=(224,224,3)))
> File "F:\anaconda\lib\site-packages\keras\applications__init__.py", line 28, in wrapper
> return base_fun(*args, **kwargs)
> File "F:\anaconda\lib\site-packages\keras\applications\resnet50.py", line 11, in ResNet50
> return resnet50.ResNet50(*args, **kwargs)
> File "F:\anaconda\lib\site-packages\keras_applications\resnet50.py", line 290, in ResNet50
> md5_hash='a268eb855778b3df3c7506639542a6af')
> File "F:\anaconda\lib\site-packages\keras\utils\data_utils.py", line 226, in get_file
> raise Exception(error_msg.format(origin, e.errno, e.reason))
> Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- unknown url type: https

No. I had not faced this issue. There is still a problem about missing avg_pol layer.
